### ISSUE TITLE
multiple tags entry

### ISSUE THREAD

**Issue by kingalex50** [tagspaces/tagspaces#807]
You can't enter multiple tags by separating them with commas.  
The previous version let you use commas to enter multiple tags.  Now even when you type commas to separate the tags, it recognizes the whole string of tags as one tag.
Now you have to enter one tag at a time.
version 3.0.0
windows 10

**Comment by uggrock** [comment]
this is fixed for the upcoming 3.0.1 version

**Comment by Xeomuz** [comment]
3.0.1 version still does not have this feature

**Comment by uggrock** [comment]
Just try to enter the tag delimited only by comma without spaces, like tag1,tag2,tag3

**Comment by rabitag** [comment]
still not working in 3.0.5
![image](https://user-images.githubusercontent.com/46843094/51427041-fd774b00-1bf2-11e9-9f9a-61ba3032a015.png)
